version: '3'

services:
  mkdocs:
    container_name: mkdocs
    image: polinux/mkdocs:1.1.2
    restart: always
    ports:
      - "8000:8000"
    environment:
      LIVE_RELOAD_SUPPORT: 'true'
      ADD_MODULES: 'mkdocs-git-revision-date-localized-plugin mkdocs-material mkdocs-awesome-pages-plugin mkdocs-markdownextradata-plugin'
      FAST_MODE: 'true'
      DOCS_DIRECTORY: '/docs'
      GIT_REPO: 'https://github.com/kafein-product-space/mkdocs-pc.git'
      UPDATE_INTERVAL: 2
      AUTO_UPDATE: 'true'
      GIT_BRANCH: main
