site_name: Kafein Product
site_url: https://documentation.netfein.com
theme:
  name: material
  logo: https://kafein.fra1.digitaloceanspaces.com/kafeinweb/kafein-logo-dikey-sb-1-1f7d6.png
  palette:
    primary: indigo
    accent: red
  features:
    - search.share
    - search.highlight
    - content.tabs.link
  language: tr
nav:
  - Home: index.md
  - Contribute: contrib.md
  - DataFocus:
    - Intro: datafocus/introduction.md
  - DataTouch:
    - Intro: datatouch/intro.md
    - About: datatouch/about.md
    - Preparation: datatouch/preparation.md
    - Docker Installation: shared/docker_installation.md
    - Architecture: datatouch/architecture.md
    - Quickstart Installation: datatouch/quickstart.md

  - TDM:
    - Intro: tdm/01_intro.md
    - About: tdm/02_about.md
  - DevOps:
    - Intro: devops/introduction.md
    - Git: devops/git.md
    - CI&CD: devops/cicd.md
  - Dökümantasyon:
    - Intro: documentation/introduction.md

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - def_list


extra: 
  version:
    provider: mike

extra_javascript:
  - js/toggle.js

extra_css:
  - css/toggle.css
